language: python
python:
    - "2.6"
    - "2.7"
    # - "3.2" Not supported by codecov.io
    - "3.3"
    - "3.4"
    - "3.5-dev"
sudo: false
before_install:
    - pip install codecov
script:
    - coverage run setup.py test
afert_success:
    - codecov
notifications:
    email: false
