language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
sudo: false
before_install:
    - pip install codecov
script:
    - coverage run setup.py test
afert_success:
    - codecov
notifications:
    email: false
